---
title: "DataPrep"
author: "Isabel R"
date: "5/12/2020"
output: html_document
---

```{r comment=false}
#Libraries
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(RColorBrewer)
```

```{r}
#Data Load
Performance_DF = read.csv("./Performance_LIRR.csv",stringsAsFactors = FALSE)
```

```{r}
head(Performance_DF)
```

```{r}
#Clean Text
clean_text <- function(x,y) {
  z = gsub(y,'', x)
  return(z)
}
```

```{r}
#Tidy Data
TidyPerformancedf = Performance_DF%>%
  filter(., Parent.Sequence == 20421 | Indicator.Sequence == 20421)%>%
  select(., Indicator.Name, Period.Month, Period.Year, 
         YTD.Target, YTD.Actual, Monthly.Target, Monthly.Actual, Period)%>%
  mutate(., Indicator.Name = clean_text(Indicator.Name,"Branch - OTP"))%>%
  mutate(., Indicator.Name = clean_text(Indicator.Name,"Branch OTP"))%>%
  mutate(., Indicator.Name = str_trim(Indicator.Name))%>%
  mutate(., Month_Name = month.name[Period.Month])

write.csv(TidyPerformancedf, file = "TidyPerformance.csv",row.names=FALSE)
```


```{r comment=FALSE,warning=FALSE}
#Data Load
df <- readr::read_csv("./TidyPerformance.csv")
```


```{r}
#Average Branch Performance
df1 = TidyPerformancedf%>%
  filter(., Indicator.Name != 'On-Time Performance')%>%
  group_by(Indicator.Name)%>%
  summarise(., Average_OTP = mean(Monthly.Actual))%>%
  arrange(.,(Average_OTP))
```


```{r}
#Tidy text
change_text <- function(x,y,z) {
  return(gsub(pattern = x, replacement = y, x = z))
}
```


```{r}
#Overall delay 
test_df = TidyPerformancedf%>%
  filter(., Indicator.Name != 'On-Time Performance')%>%
  filter(., Indicator.Name != 'Hicksville/Huntington')%>%
  group_by(., Indicator.Name)%>%
  summarise(., Average_OTP = mean(Monthly.Actual))%>%
  arrange(., desc(Average_OTP))
```



